services:
  - type: web
    name: bgio-ttt
    env: node
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://carabennett.github.io,https://carabennett.github.io/secretwall,http://localhost:5173
